export default {
    GET_COMMENTS: 'GET_COMMENTS',
    SET_COMMENTS: 'SET_COMMENTS',
    DEL_COMMENT: 'DEL_COMMENT',

    GET_BLOGS: 'GET_BLOGS',
    SET_BLOGS: 'SET_BLOGS',
    DEL_BLOG: 'DEL_BLOG',
    UPDT_BLOG: 'UPDT_BLOG',
    ADD_BLOG: 'ADD_BLOG',
    CHANGE_EDIT_STATE: 'CHANGE_EDIT_STATE',
    CHANGE_SEARCH_TYPE: 'CHANGE_SEARCH_TYPE',

    GET_USERS: 'GET_USERS',
    SET_USERS: 'SET_USERS',
    ADD_USER: 'ADD_USER',
    STOP_USER: 'STOP_USER',
    DEL_USER: 'DEL_USER',
    CHANGE_ADD_STATE: 'CHANGE_ADD_STATE',

    LOGIN: 'LOGIN',
    SET_ADMIN_INFO: 'SET_ADMIN_INFO',
    LOGOUT: 'LOGOUT',
    INIT_INFO: 'INIT_INFO'

}